name: Filter List Update
on:
  schedule:
    - cron: "55 0 * * *"   
  workflow_dispatch: 

jobs:
  gist_update:
    name: Build the project, fetch filter lists, and push the filter lists to the gist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build and run docker containers
        run: ./.docker/single-build.sh

      - name: Wait Docker-Compose Healthy
        # uses: thegabriele97/dockercompose-health-action@d1003e3654befbe25146b613b823e39d5002e067
        uses: thegabriele97/dockercompose-health-action@v2024.04.19.0
        with:
          filename: 'dual-container-compose.yml'
          timeout: '60'
          workdir: '.docker'

      - name: Save to file
        run: curl "http://127.0.0.1:5000/ublock" > ublock.txt
          && curl "http://127.0.0.1:5000/ublacklist" > ublacklist.txt
          && curl "http://127.0.0.1:5000/plain" > plain.txt
        
      - name: Publish uBlock to gist
        # uses: Popsiclestick/gist-sync-action@88f8633178625914f2a01abf1a765f7272a580fa
        uses: Popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/JonasLong/82e98e4072ba592f130edc53cdaa386d
          gist_title: DeGrabify uBlock Blocklist
          gist_description: A set of filter lists that update to block the latest in-use Grabify domains. See https://github.com/JonasLong/DeGrabify for the full project.
          github_file: ublock.txt
      
      - name: Publish uBlacklist to gist
        # uses: Popsiclestick/gist-sync-action@88f8633178625914f2a01abf1a765f7272a580fa
        uses: Popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/JonasLong/82e98e4072ba592f130edc53cdaa386d
          gist_title: DeGrabify uBlacklist Blocklist
          gist_description: A set of filter lists that update to block the latest in-use Grabify domains. See https://github.com/JonasLong/DeGrabify for the full project.
          github_file: ublacklist.txt
      
      - name: Publish plain URLs to gist
        # uses: Popsiclestick/gist-sync-action@88f8633178625914f2a01abf1a765f7272a580fa
        uses: Popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/JonasLong/82e98e4072ba592f130edc53cdaa386d
          gist_title: DeGrabify Plain Domain Blocklist
          gist_description: A set of filter lists that update to block the latest in-use Grabify domains. See https://github.com/JonasLong/DeGrabify for the full project.
          github_file: plain.txt
      
